export const LOAD_PROPERTIES = Symbol("LOAD_PROPERTIES");
export const LOAD_PROPERTIES_SUCCESS = Symbol("LOAD_PROPERTIES_SUCCESS");
export const LOAD_PROPERTIES_ERROR = Symbol("LOAD_PROPERTIES_ERROR");

export const LOAD_FAVORITES = Symbol("LOAD_FAVORITES");
export const LOAD_FAVORITES_SUCCESS = Symbol("LOAD_FAVORITES_SUCCESS");
export const LOAD_FAVORITES_ERROR = Symbol("LOAD_FAVORITES_ERROR");
